api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
    eager_loading:
        force_eager: true
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
