version: '3.7'

services:
    nginx:
        build: docker/nginx
        container_name: nginx
        volumes:
            - dev-certs:/etc/ssl:ro
            - ./:/symfony:cached
        links:
            - php
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        environment:
            - VIRTUAL_HOST=api.chat.local

    php:
        build: docker/php
        container_name: php
        volumes:
            - ./:/symfony:cached
        links:
            - db

    db:
        build: docker/mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: chat
            MYSQL_DATABASE: chat
            MYSQL_USER: chat
            MYSQL_PASSWORD: chat
        volumes:
            - "./var/db:/var/lib/mysql"
        ports:
            - "3306:3306"

    mercure:
        image: dunglas/mercure
        environment:
            - ALLOW_ANONYMOUS=1
            - CERT_FILE=/certs/localhost.crt
            - CORS_ALLOWED_ORIGINS=*
            - DEMO=1
            - JWT_KEY=!ChangeMe!
            - KEY_FILE=/certs/localhost.key
            - PUBLISH_ALLOWED_ORIGINS=https://localhost:1337 # required for publishing from the demo page
        depends_on:
            - dev-tls
        volumes:
            - dev-certs:/certs:ro
        ports:
            - target: 1337
              published: 1337
              protocol: tcp

    dev-tls:
        build:
            context: ./docker/dev-tls
        volumes:
            - dev-certs:/certs:rw

volumes:
    dev-certs: {}