version: '3'

services:
    nginx:
        build: docker/nginx
        container_name: nginx
        volumes:
            - ./:/symfony:cached
        links:
            - php
        depends_on:
            - php
        ports:
            - "80:80"

    php:
        build: docker/php
        container_name: php
        volumes:
            - ./:/symfony:cached
        links:
            - db

    db:
        build: docker/mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: chat
            MYSQL_DATABASE: chat
            MYSQL_USER: chat
            MYSQL_PASSWORD: chat
        volumes:
            - "./var/db:/var/lib/mysql"
        ports:
            - "3306:3306"
