App\Entity\User:
  attributes:
    normalization_context:
      groups: ['user', 'user:read']
    denormalization_context:
      groups: ['user', 'user:write']
  collectionOperations:
    get:
      security: "is_granted('ROLE_USER')"
    post:
      validation_groups: ['post:user']
  itemOperations:
    get:
      security: "is_granted('ROLE_USER')"
    put:
      security: "is_granted('ROLE_ADMIN') or object === user"
      validation_groups: ['put:user']
    delete:
      security: "is_granted('ROLE_ADMIN') or object === user"
